[env:seeed_xiao_nrf52840_bluefruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoble_adafruit
framework = arduino

monitor_speed = 115200

# WARNING: DO NOT REMOVE extra_scripts
# The Adafruit nRF52 Arduino Core uses Adafruit TinyUSB, which automatically
# includes SdFat (for Mass Storage). SdFat defines a `File` class.
# This project uses Adafruit_LittleFS, which *also* defines a `File` class.
# extra_script.py injects a wrapper (`include_fix/Adafruit_TinyUSB.h`)
# to hide the SdFat version during framework compilation, preventing ambiguous
# File class errors.
extra_scripts = pre:extra_script.py

lib_deps =
  afantor/Bluefruit52_Arduino
  adafruit/Adafruit TinyUSB Library

build_flags =
  -D UGUISU_BUILD_PIO=1
  -I ".pio/libdeps/seeed_xiao_nrf52840_bluefruit/Adafruit TinyUSB Library/src"
