[env:seeed_xiao_nrf52840_bluefruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoble_adafruit
framework = arduino

monitor_speed = 115200

lib_deps =
  afantor/Bluefruit52_Arduino
  adafruit/Adafruit TinyUSB Library

build_flags =
  -D UGUISU_BUILD_PIO=1

