[env:seeed_xiao_nrf52840_bluefruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoble_adafruit
framework = arduino

monitor_speed = 115200

lib_deps =
  afantor/Bluefruit52_Arduino
  adafruit/Adafruit TinyUSB Library
  SPI

lib_ldf_mode = deep+

build_flags =
  -I ".pio/libdeps/seeed_xiao_nrf52840_bluefruit/Adafruit TinyUSB Library/src"
  -D CFG_TUSB_CONFIG_FILE=\"immo_tusb_config.h\"
  -I lib/ImmoCommon/src
